# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 543391c90f45dd6f2784635aedbd14df6583d090d29ae201c764cd56e8860b086ae62151429562a824b7d3415d88c485e605428982ee9886adf3dff524647747

test:
  secret_key_base: 1b9949978ee9bacce0c6551a172d70661f9f19d57e637e3cf21fcde0a98660b7cde71d89431160bfd507e57faca0abe1a2587ee8882c876468dc60b05ddec36a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
